#!/usr/bin/env python3.2

from __future__ import division, print_function

import sys

from argparse import ArgumentParser, FileType

from Bio import AlignIO

from hy454 import (COVERAGE, MAJORITY,
    graph_coverage_majority)


def main(infile, mode, outfile, refidx):
    msa = AlignIO.read(infile, 'fasta')

    graph_coverage_majority(
        msa,
        mode,
        outfile,
        format='pdf',
        refidx=refidx
    )

    return 0


if __name__ == '__main__':
    parser = ArgumentParser(
        description='draw a coverage and/or majority graph of a multiple sequence alignment'
    )
    parser.add_argument(
        'input',
        metavar='MSA',
        type=FileType('r'),
        help='aligned FASTA file'
    )
    parser.add_argument(
        'output',
        metavar='PDF',
        help='output PDF file'
    )
    parser.add_argument(
        '-c', '--coverage',
        action='store_const',
        const=COVERAGE, default=0,
        help='include a coverage plot in the graph'
    )
    parser.add_argument(
        '-m', '--majority',
        action='store_const',
        const=MAJORITY, default=0,
        help='include a majority plot in the graph'
    )
    parser.add_argument(
        '-r', '--refidx',
        type=int, default=0,
        help='omit reference sequence which is REFIDX-th in the file (1-indexed)'
    )

    ns = None
    retcode = -1
    try:
        ns = parser.parse_args()
        retcode = main(ns.input, ns.coverage | ns.majority, ns.output, ns.refidx - 1)
    finally:
        if ns is not None:
            if not ns.input in (None, sys.stdin):
                ns.input.close()
    sys.exit(retcode)
