#!/usr/bin/env python2.7

import sys

from os.path import exists

from hy454 import align_to_refseq
from Bio import SeqIO, AlignIO


def main(argv=None):
    if argv is None:
        argv = sys.argv[1:]

    if len(argv) not in (1, 2) or not exists(argv[0]):
        print >> sys.stderr, 'usage: codonaligner FASTAFILE [OUTPUTFILE]'
        sys.exit(-1)

    with open(argv[0], 'r') as fh:
        seqrecords = [r for r in SeqIO.parse(fh, 'fasta')]

    refseq = seqrecords.pop(0)

    msa = align_to_refseq(refseq, seqrecords)

    if len(argv) == 2:
        with open(argv[1], 'w') as fh:
            AlignIO.write(msa, fh, 'fasta')
    else:
        AlignIO.write(msa, sys.stdout, 'fasta')

    return 0


if __name__ == '__main__':
    sys.exit(main())
