#!/usr/bin/env python2.7

import sys

from os.path import exists

from hy454 import align_to_refseq
from Bio import SeqIO, AlignIO


def main(argv=None):
    if argv is None:
        argv = sys.argv[1:]

    if len(argv) != 1 or not exists(argv[0]):
        print >> sys.stderr, "usage: codonaligner FASTAFILE"
        sys.exit(-1)

    with open(argv[0], 'r') as fh:
        seqrecords = [r for r in SeqIO.parse(fh, "fasta")]

    refseq = seqrecords[0]
    seqrecords = seqrecords[1:]

    msa = align_to_refseq(refseq, seqrecords)

    AlignIO.write(msa, sys.stdout, "fasta")

    return 0


if __name__ == '__main__':
    sys.exit(main())
